### ISSUE TITLE
'O2' defaults to the inert O=O form instead of [O][O] in kinetics search

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-website#84] opened 2015-05-20 04:21 UTC
Searching for reactions with O2 in the kinetics search doesn't lead to any reactions, because the default interpretation is the inert version with double bonds and lone pairs.

**Comment by connie** [comment] 2015-05-20 12:53
I think we still require [O][O] SMILES.  But we should change the default setting for the interpreter for O2 to be [O][O].

**Comment by pierrelb** [comment] 2015-05-26 18:58
Closed as a duplicate of issue #46.

**Closed by pierrelb** 2015-05-26 18:58 UTC

**Comment by rwest** [comment] 2015-05-26 19:03
Well noticed, Pierre. The fact that issue #46 has been open for three years without being fixed is a bit disappointing. Put it on the summer-student wish-list?
